name: Maven Checks

on:
  push:
    branches:
      - master

env:
  jsonSecretKey: 'fakeSecretKey'
  frontendDomainUrl: 'http://localhost:5173'
  ekartBackendPassword: 'fakeEkartBackendPassword'
  stripeApiKey: 'fake-stripe-api-key'
  adminPassword: 'fakeAdminPassword'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      - name: Build with Maven
        run: mvn clean install

      - name: Verify the build
        run: mvn verify

      - name: Run tests
        run: mvn test